export const DOCUMENT__BODY_HAS_NO_COOKIE_CONSENT_FORM = new Error("DOCUMENT__BODY_HAS_NO_COOKIE_CONSENT_FORM");
export const CCF_TEXT_HAS_NO_COOKIE_CONSENT_FORM       = new Error("CCF_TEXT_HAS_NO_COOKIE_CONSENT_FORM");
export const CCF_SELECTOR_INVALID                      = new Error("CCF_SELECTOR_INVALID");
export const CLAUDE_INVALID_RESPONSE                   = new Error("CLAUDE_INVALID_RESPONSE");