export const DOCUMENT__BODY_HAS_NO_COOKIE_CONSENT_FORM = "DOCUMENT__BODY_HAS_NO_COOKIE_CONSENT_FORM";
export const CCF_TEXT_HAS_NO_COOKIE_CONSENT_FORM      = "CCF_TEXT_HAS_NO_COOKIE_CONSENT_FORM";
export const CCF_SELECTOR_INVALID                     = "CCF_SELECTOR_INVALID";

export const CLAUDE_INVALID_RESPONSE = "CLAUDE_INVALID_RESPONSE";